name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache dependency
      uses: actions/cache@v1
      with:
        path: .gradle
        key: dependency-${{ hashFiles('build.gradle') }}
        restore-keys: |
          dependency-${{ env.cache-name }}-
          dependency-
          dependency
    - name: Build with Gradle
      run: ./gradlew build
